### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password",
  "account_id": 12345678
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "lucas@example.com",
  "password": "password"
}

### User update
PATCH  http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer 

{
  "account_id": 188172182
}

### Players Index / Show
GET http://localhost:3000/players
Content-Type: application/json

### Player Create to Rails database
POST http://localhost:3000/players
Content-Type: application/json

{
  "account_id": 898754153
}

### Players Update / Refresh
PATCH http://localhost:3000/players/4
Content-Type: application/json

{
  "account_id": 157475523
}

### Following List Create
POST http://localhost:3000/followings
Content-Type: application/json
Authorization: Bearer 

{
  "player_id": 4
}

### Following List Update
PATCH http://localhost:3000/followings/4
Content-Type: application/json
Authorization: Bearer 

{
  "player_id": 3
}

### Following List Delete
DELETE http://localhost:3000/followings/2

### Recent Matches
# GET http://localhost:3000/recent
# Content-Type: application/json
# Authorization: Bearer 